export const SHOW_COMPONENT: 'SHOW_COMPONENT' = 'SHOW_COMPONENT';
export const HIDE_ANIMATION_START: 'HIDE_ANIMATION_START' = 'HIDE_ANIMATION_START';
export const HIDE_ANIMATION_FINISHED: 'HIDE_ANIMATION_FINISHED' = 'HIDE_ANIMATION_FINISHED';
