export const SHOW_COMPONENT: 'SHOW_COMPONENT' = 'SHOW_COMPONENT';
export const START_HIDE_ANIMATION: 'START_HIDE_ANIMATION' = 'START_HIDE_ANIMATION';
export const HIDE_ANIMATION_FINISHED: 'HIDE_ANIMATION_FINISHED' = 'HIDE_ANIMATION_FINISHED';
