export const SHOW_MODAL: 'SHOW_MODAL' = 'SHOW_MODAL';
export const HIDE_ANIMATION_START: 'HIDE_ANIMATION_START' = 'HIDE_ANIMATION_START';
export const HIDE_ANIMATION_FINISHED: 'HIDE_ANIMATION_FINISHED' = 'HIDE_ANIMATION_FINISHED';
